name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/tests.yaml
  pull_request:
    branches: [main]
    paths:
      - Sources/**
      - Tests/**
      - .github/workflows/tests.yaml

env:
  CODE_SIGNING_REQUIRED: NO
  CODE_SIGN_IDENTITY: ""

jobs:
  build:
    name: Build
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            "platform=iOS Simulator,name=iPhone SE (2nd generation)",
            "platform=macOS",
            "platform=tvOS Simulator,name=Apple TV",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install XCBeautify
        run: brew install xcbeautify

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData/*
          key: ios-cache-
          restore-keys: ios-cache-

      - name: Run Build ${{ matrix.platform }}
        run: |
          cd .swiftpm/xcode
          xcodebuild build \
            -destination "${{ matrix.platform }}" \
            -workspace package.xcworkspace \
            -scheme StatsigOnDeviceEvaluations \
            | xcbeautify && exit ${PIPESTATUS[0]}

  test:
    name: Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install XCBeautify
        run: brew install xcbeautify

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData/*
          key: ios-cache-
          restore-keys: ios-cache-

      - name: Lint Podspec
        run: pod lib lint StatsigOnDeviceEvaluations.podspec --skip-tests

      - name: Run Tests
        run: ./run_tests.sh
