name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CODE_SIGNING_REQUIRED: NO
  CODE_SIGN_IDENTITY: ""

jobs:
  build:
    name: Build
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            "platform=iOS Simulator,name=iPhone SE (2nd generation)",
            "platform=macOS",
            "platform=tvOS Simulator,name=Apple TV",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run Build ${{ matrix.platform }}
        run: |
          cd .swiftpm/xcode
          xcodebuild build \
            -destination "${{ matrix.platform }}" \
            -workspace package.xcworkspace \
            -scheme StatsigOnDeviceEvaluations \
            | xcbeautify && exit ${PIPESTATUS[0]}

  test:
    name: Test
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Lint Podspec
        run: pod lib lint StatsigOnDeviceEvaluations.podspec --skip-tests

      - name: Run Tests
        run: ./run_tests.sh
